### ISSUE TITLE
Cursor option should not autoload

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-bulk-task#13]
### Description of the bug

The option saved by `Cursor` [does not specify an `$autoload` parameter](https://github.com/alleyinteractive/wp-bulk-task/blob/fed089850e35d4542920c4016389f01c0ca4ddba/src/class-cursor.php#L60), and is therefore autoloaded, but I can't think of any reason why it should be.

### Steps To Reproduce

1. Run a bulk task.
2. Observe that the `bt_{$task}` option is has an `autoload` of `yes`.

**Comment by renatonascalves** [comment]
I don't either. But I don't think this is a bug since this option would only be harmfull if it was large in size.

**Comment by dlh01** [comment]
True, the option is not large, but what if you have 50 bulk tasks? That's 50 additional rows to be pulled by the autoload database query. If you run a couple of tasks with a dynamic key — for example, if the key is based on a category ID — it seems quite possible that you would end up with an even larger number of cursors in the database.

**Comment by renatonascalves** [comment]
Agree! I plan on fixing this soon. I agree it is a problem, I just don't agree it is a bug, yet. =P
